# ======================== Server ========================
port: 52696
#  ============== LLM Backend Settings ===================
# LLM_URL: "http://localhost:11434/v1/"
llm_url: "http://localhost:11434/"
api_key: "key"
organization_id: "org id"
project_id: "proj id"
model: "llama3:latest" 
# ===================== TTS Settings ====================== 
tts_mode: "edgeTTS"
edge:
  voice: "en-US-EmmaNeural"
  pitch: "+10Hz"
 
bless: True