# ======================== Server ========================
PORT: 52696

#  ============== LLM Backend Settings ===================
# LLM_URL: "http://localhost:11434/v1/"
LLM_URL: "http://localhost:11434/"
API_KEY: "key"
ORGANIZATION_ID: "org_id
PROJECT_ID: "proj_id"
MODEL: "llama3:latest" 